export const CATEGORIES = {
  CALDOS: 'CALDOS',
  CHICHARRONES: 'CHICHARRONES',
  MIXTOS: 'MIXTOS',
  POLLOS: 'POLLOS',
  ENSALADAS: 'ENSALADAS',
  ARROCES: 'ARROCES',
  PESCADOS: 'PESCADOS',
  PASTAS: 'PASTAS'
};
